import { random, takeRandom, takeWeightedRandom } from "./utilities.ts";

export type Building = {
  features: string[];
  possibleSecret: string;
  state: string;
  style: string;
  type: string;
  unusualFeature: string;
};

export function generateBuilding() {
  return {
    features: [takeRandom(features), takeRandom(features)],
    possibleSecret: takeRandom(secrets),
    state: takeRandom(states),
    style: takeRandom(styles),
    type: takeWeightedRandom(types),
    unusualFeature: takeRandom(unusualFeatures),
  };
}

export var types = [
  [2, "Pharmacy"],
  [2, "Consumer Electronics"],
  [1, "Art Dealer or Gallery"],
  [1, "Auto or Robotics Repair"],
  [1, "Storage Units or Warehousing"],
  [1, "Legal Firm"],
  [2, "Religious Building"],
  [2, "Capsule Hotel"],
  [1, "Data Storage"],
  [3, "Low Rent Housing Project"],
  [2, "Grocery Store or Hypermarket"],
  [1, "Elevated Rail or Road Overpass"],
  [3, "Fast Food Franchise"],
  [2, "Police Precinct"],
  [1, "School or College"],
  [2, "Government Building"],
  [1, "Garage or Parking Block"],
  [4, "Office Block"],
  [2, "Public Transport Hub"],
  [2, "Hospital or Clinic"],
  [2, "Department Store"],
  [3, "Body Augmentation Clinic"],
  [2, "Luxury Apartments"],
  [2, "News Media Company"],
  [2, "Industrial"],
  [1, "Security Tech"],
  [2, "Vehicle Showroom"],
  [2, "Fashion Boutique"],
  [2, "Commercial Cybernetics"],
  [1, "Mall"],
  [1, "Vrcade"],
  [1, "Gym"],
  [1, "Leisureplex"],
  [5, "Apartment Block or Hab Stack"],
  [3, "Nightclub"],
  [1, "Underpass"],
  [3, "Hotel"],
  [2, "Ripperdoc"],
  [2, "3-D Print Fabrication"],
  [2, "Courier or Bulk Transport Company"],
  [3, "Bar"],
  [2, "Restaurant"],
  [2, "Pop-up Market"],
  [2, "Coffee Shop"],
  [1, "Taxi Firm"],
  [2, "Pocket Park"],
  [2, "Suburban Housing"],
  [1, "Movie Theater"],
  [1, "Weapons Tech or Sales"],
  [2, "Multi-Level Car Park"],
  [1, "Bank"],
  [1, "Antiques"],
];

export var features = [
  "“Grown” By Nanites",
  "A Crime Scene",
  "A Riot Of Satellite Dishes",
  "AI Guardian",
  "Abandoned Edifice",
  "Accumulated Trash Heaps",
  "Aggressively Enforced No-Parking Zone",
  "Anti-Drone System",
  "Augmented Reality Heavy",
  "Back room Brothel",
  "Bad Wiring; High EMF; Black Outs",
  "Being Audited By Fanatical City Inspectors",
  "Bright Emoji Glyphs And Graphics",
  "Brutalist",
  "Buggy Security Net",
  "Catastrophically Polluted",
  "Causes Sickness",
  "Cellular Black Hole",
  "Chic And Minimalist",
  "Completely Automated",
  "Crumbling Cheapcrete",
  "Decrepit And rundown",
  "Ecologically Sound; No Carbon Footprint",
  "Elaborate Balconies",
  "Empty/Quiet",
  "Encased In Plastic Siding",
  "Endorsed By Celebutant",
  "Enforced No Fly Zone",
  "Exotic/Foreign Architecture",
  "Extensive Drone Docks",
  "Extreme Security Protocols",
  "Extremely leaky",
  "Family Owned",
  "Fire Damage",
  "For Sale/To-let",
  "Foreign Ghetto",
  "Front for Corporate Activity",
  "Front for Criminal Activity",
  "Gothic Style",
  "Graffitipocalypse/Street Art Heavy",
  "Hidden Squatters",
  "High Tech Equipment",
  "Homeless Magnet",
  "Inadequate Security",
  "Incomplete",
  "Independent Nation State",
  "Industrial Style",
  "Infested With rogue remotes",
  "Labyrinthine",
  "Legacy Infrastructure",
  "Main Entrance Out Of Order",
  "Mainly Populated By Hoarders",
  "Malfunctioning Incessant Alarm",
  "Nano Immune System",
  "Newly renovated",
  "Not A Building, But Mobile",
  "Obscured By Ad Screens",
  "Obvious Corporate Sponsor",
  "Obvious Gang Turf",
  "Patrolled by Hired Rent-A-Cops",
  "People Queue to enter",
  "Permadamp",
  "Popular With Particular Subculture",
  "Promotes religion",
  "Prone To Flooding",
  "Rat Or Roach Problem",
  "Reinforced for repair Work",
  "Repurposed As (Building)",
  "Scheduled For Demolition",
  "Security Camera Overkill",
  "Selective Access",
  "Self Aware",
  "Self Sufficient",
  "Several Trashed Cars Out Front",
  "Shakes When Trucks Pass",
  "Skywalks To Other Buildings",
  "Slowly Collapsing Or Subsiding",
  "Sweatshop Conditions",
  "Taken Over By Junkies",
  "Target Of Net Terrorism",
  "Tinted Glass And Carbon Nano-Tubes",
  "Totally Sterile",
  "Under Surveillance",
  "Unfinished Extension Or Empty levels",
  "Unpleasant Micro-Climate",
  "Unusual Smell",
  "Unusually Busy",
  "Utilized Solely For Storage",
  "Very Few Working lights",
  "Very Noisy utilities",
  "War Zone",
  "Well Guarded",
  "Wind Tunnel",
  "Windows Boarded With Opaque Acrylic",
  "Years Of Clumsy Modification",
];

var secrets = [
  "Cameras",
  "Microphone",
  "Separate LAN",
  "Custodian AI",
  "Weapon Sensor",
  "Weapons Cache",
];

var states = [
  "Cavernous",
  "Cluttered",
  "Cramped",
  "Organized",
  "Pristine",
  "Spacious",
  "Sterile",
  "Untidy",
];

var styles = [
  "(Bio)Organic",
  "Brushed Steel",
  "Gothic",
  "Hexagonal Tiles",
  "Industrial",
  "Minimalist",
  "Office Beige",
  "Polymer Baroque",
  "Rustic",
  "Shabby-Chic",
];

var unusualFeatures = [
  "Artificial Plants",
  "Biohazard",
  "Holograms",
  "Hydroponics",
  "Legacy Tech",
  "Monochromatic",
  "Remote Assistants",
  "Scavenged Furniture",
  "Strange Acoustics",
];
